//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHotels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int idCl { get; set; }
        public int idHot { get; set; }
        public string comm { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
