//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHotels.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelsDataBaseEntities : DbContext
    {
        public HotelsDataBaseEntities()
            : base("name=HotelsDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<chambre> chambre { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commentaire> Commentaire { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
        public virtual DbSet<servicee> servicee { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<images> images { get; set; }
    }
}
